
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 817383
	#The name of the modpack
	modpackName = "A Lord's Call"
	#The version of the modpack
	modpackVersion = "ALC 0.0.1-1.18.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

